### ISSUE TITLE
Dark mode

### ISSUE THREAD

**Issue by pierrbt** [Encode42/minecrafts.date#2]
When I switch between dark and light mode, there is a 500 HTTP error and the CSS stop working (Android - Chrome)
![Screenshot_2022-08-07-18-33-54-823_com.android.chrome.jpg](https://user-images.githubusercontent.com/83456236/183301388-1b2f336a-d696-402f-9ad4-c4ff59a11aad.jpg)

![Screenshot_2022-08-07-18-34-39-921_com.android.chrome.jpg](https://user-images.githubusercontent.com/83456236/183301415-1d695a24-88de-407e-b821-935c28ebb863.jpg)

**Comment by encode42** [comment]
Fixed in 80c35a61384eb45d38806ce77aa41f05b2f0622c

**Comment by pierrbt** [comment]
It works perfect by now, good job !
![Screenshot_2022-08-07-21-59-19-854_com.android.chrome.jpg](https://user-images.githubusercontent.com/83456236/183308992-e0324403-42d8-48b2-90fe-eecff5f24450.jpg)
(the dark mode stay better according ton me 😅 but now it works !)
